version: 2

updates:
  - package-ecosystem: gomod
    directory: /server/backend
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /server/frontend
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
