apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: university-app-backend
    newTag: local
  - name: university-app-frontend
    newTag: local