apiVersion: v1
kind: Secret
metadata:
  name: university-app-secrets
type: Opaque
stringData:
  db-password: change-me-db-password
  jwt-secret-key: change-me-jwt-secret
  qr-secret-key: change-me-qr-secret